services:
  - type: web
    name: app-auditorias
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && cd frontend-app && npm install && npm run build && cd .. && alembic upgrade head"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker backend.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: app-auditorias-db
          property: connectionString

databases:
  - name: app-auditorias-db
    databaseName: app_auditorias_b5oy
    user: app_auditorias_b5oy_user
    region: oregon
    plan: free
